encrypt:
  key: "57CD4EC2CEE43229E4CFAE6B18BA5"

server:
  port: 18071

spring:
  application:
    name: "configserver"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Mazaadak/mazaadak-configs.git"
          username: mazadak-bot
          password: ${MAZADAK_GITHUB_TOKEN}
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 30
          skip-ssl-validation: true

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true